k

diff --git a/config b/config
--- a/config
+++ b/config
@@ -57,8 +57,8 @@ _a() {
 
 #──────────────────────────────────────────────────────────  functions  ───────
 
-shutdown_guest_vm() {
-  
+shutdown_guest_vm()
+{
   l_try=0
 
   ssh "${esxiuser}"@"${esxihost}" vim-cmd vmsvc/power.getstate $1 | grep -i "off" > /dev/null 2<&1
@@ -67,24 +67,29 @@ shutdown_guest_vm() {
 #  printf "VM [%s] status=[%s]\n" "$1" "${l_status}"
 
   if [ $l_status -eq 0 ]; then
-    _e "Guest VM ID $1 already powered down..."
+    echo "Guest VM ID $1 already powered down..."
   else
     while [ $l_try -lt $waitretries ] && [ $l_status -ne 0 ]; do
       l_try=$((l_try+1))
-      ssh "${esxiuser}"@"${esxihost}" vim-cmd vmsvc/power.shutdown $1 > /dev/null 2<&1
-      _e "Waiting ${waitdelay} seconds for guest VM ID $1 to shutdown (attempt $l_try of $waitretries)..."
-      sleep $waitdelay
-      ssh "${esxiuser}"@"${esxihost}" vim-cmd vmsvc/power.getstate $1 | grep -i "off" > /dev/null 2<&1
-      l_status=$?
+      if [ $dryrun -ne 0 ]; then
+        echo "TEST MODE: Would issue shutdown command and wait ${waitdelay} seconds for guest VM ID $1 to shutdown (attempt $l_try of $waitretries)..."
+      else
+        ssh "${esxiuser}"@"${esxihost}" vim-cmd vmsvc/power.shutdown $1 > /dev/null 2<&1
+        echo "Waiting ${waitdelay} seconds for guest VM ID $1 to shutdown (attempt $l_try of $waitretries)..."
+        sleep $waitdelay
+        ssh "${esxiuser}"@"${esxihost}" vim-cmd vmsvc/power.getstate $1 | grep -i "off" > /dev/null 2<&1
+        l_status=$?
+#	printf "VM [%s] status=[%s] try=[%s]\n" "$1" "${l_status}" "${l_try}"
+      fi
     done
     if [ $l_status -eq 0 ]; then
-      _e "Shutdown sucessful on attempt ${l_try}..."
+      echo "Shutdown sucessful on attempt ${l_try}..."
       totalvmsshutdown=$((totalvmsshutdown + 1))
     else
       if [ $dryrun -ne 0 ]; then
-        _e "TEST MODE: Unable to gracefully shutdown guest VM ID $1, would force power off and wait ${waitdelay} seconds before checking status."
+        echo "TEST MODE: Unable to gracefully shutdown guest VM ID $1, would force power off and wait ${waitdelay} seconds before checking status."
       else
-        _e "Unable to gracefully shutdown guest VM ID $1... forcing power off."
+        echo "Unable to gracefully shutdown guest VM ID $1... forcing power off."
         ssh "${esxiuser}"@"${esxihost}" vim-cmd vmsvc/power.off $1 > /dev/null 2<&1
         sleep $waitdelay
       fi
@@ -96,8 +101,50 @@ shutdown_guest_vm() {
       fi
     fi
   fi
-
 }
+
+
+#shutdown_guest_vm() {
+#  
+#  l_try=0
+#
+#  ssh "${esxiuser}"@"${esxihost}" vim-cmd vmsvc/power.getstate $1 | grep -i "off" > /dev/null 2<&1
+#  l_status=$?
+#
+##  printf "VM [%s] status=[%s]\n" "$1" "${l_status}"
+#
+#  if [ $l_status -eq 0 ]; then
+#    _e "Guest VM ID $1 already powered down..."
+#  else
+#    while [ $l_try -lt $waitretries ] && [ $l_status -ne 0 ]; do
+#      l_try=$((l_try+1))
+#      ssh "${esxiuser}"@"${esxihost}" vim-cmd vmsvc/power.shutdown $1 > /dev/null 2<&1
+#      _e "Waiting ${waitdelay} seconds for guest VM ID $1 to shutdown (attempt $l_try of $waitretries)..."
+#      sleep $waitdelay
+#      ssh "${esxiuser}"@"${esxihost}" vim-cmd vmsvc/power.getstate $1 | grep -i "off" > /dev/null 2<&1
+#      l_status=$?
+#    done
+#    if [ $l_status -eq 0 ]; then
+#      _e "Shutdown sucessful on attempt ${l_try}..."
+#      totalvmsshutdown=$((totalvmsshutdown + 1))
+#    else
+#      if [ $dryrun -ne 0 ]; then
+#        _e "TEST MODE: Unable to gracefully shutdown guest VM ID $1, would force power off and wait ${waitdelay} seconds before checking status."
+#      else
+#        _e "Unable to gracefully shutdown guest VM ID $1... forcing power off."
+#        ssh "${esxiuser}"@"${esxihost}" vim-cmd vmsvc/power.off $1 > /dev/null 2<&1
+#        sleep $waitdelay
+#      fi
+#      ssh "${esxiuser}"@"${esxihost}" vim-cmd vmsvc/power.getstate $1 | grep -i "off" > /dev/null 2<&1
+#      l_status=$?
+##      printf "VM [%s] status=[%s]\n" "$1" "${l_status}"
+#      if [ $l_status -eq 0 ]; then
+#        totalvmspowereddown=$((totalvmspowereddown + 1))
+#      fi
+#    fi
+#  fi
+#
+#}
 
 #────────────────────────────────────────────────────────  unnecessary  ───────
 
